spring:
  h2:
   console:
    enabled: true
    path: /h2

  datasource:
    url: jdbc:h2:file:/Volumes/Dados/Desenvolvimento/Projetos/java/databases/desafio.db
    username: sa
    password:
    driver-class: ordg.h2.Driver
  jpa:
    hibernate.ddl-auto: update

jwt:
    secret: abc1234567890qwerqs

logging.level.org.springframework.web: DEBUG
logging.level.org.hibernate: ERROR